---
title: "Protocol"
author: "Rick O. Gilmore"
date: "`r Sys.time()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

This document describes the protocol the Gilmore Lab members are using to conduct a review and meta-analysis of the published literature on the development of motion sensitivity in infants, children, and adolescents.

## Protocol

### Search protocol

1. Phase I
2. Phase II

Look within papers we've tagged for references.

- Goals:
    1. review the literature about the development of motion perception (and brain responses to motion).
    2. if possible, do a meta-analysis.
- Action steps:
    - Search terms (in [Google Scholar](https://scholar.google.com/))
        - motion coherence children (unquoted)
        - motion perception children (unquoted)
        - motion perception review (unquoted)
            - source of primary references
        - motion perception review development (unquoted)
            - source of primary references
        - motion perception infants (unquoted)
            - Since 2014
    - Search time period
        - Open...
    - Species
        - human only, no non-human animals
    - Add to PaperPile
    - Measure types
        - Behavioral responses
        - Brain measures if there are behavioral data
        - Brain responses only (e.g., our SSVEP)
    - How to gather sources
        - Google Scholar search
        - Tag on PaperPile with `motion-metaanalysis`
    - How to evaluate/code sources
        - Complete entry for each source on Google sheet: <https://docs.google.com/spreadsheets/d/1j6IeyOxoOYAlPrhivEqNRWCbDZ2FkjQ0iBY8C4kdi6o/edit?usp=sharing>
            - Phase I focuses on subset of variables (not stimulus parameters, availability of data, suitability for meta-analysis)
        - Stimulus type
            - motion coherence, random dot kinematograms
                - Video exemplars
                    - <https://youtu.be/7OdCe95IiLw>
            - biological motion
                - Video exemplars
                    - <https://www.biomotionlab.ca/html5-bml-walker/>
            - gratings/plaids
                - Video exemplar:
            - optic flow
                - Video exemplar:
                    - <https://nyu.databrary.org/slot/9803/-/asset/11171/download?inline=true>
        - Stimulus parameters
            - Speed
            - Pattern type (linear/uniform)
            - Direction
            - Noise/coherence
            - Spatial characteristics (spatial frequency, dot size, display size, ...)
            - Temporal characteristics (duration, frequency)
        - Person characteristics
            - Autism Spectrum Disorder (ASD)
            - [amblyopia](https://nei.nih.gov/health/amblyopia)
            - typically developing
        - Age 
            - https://www.healthychildren.org/English/ages-stages/Pages/default.aspx
            - Newborns (0-4wk), baby(0-12 mo), toddler (1-3 yr), preschool (3-5 yr), gradschooler (5-12 yr), teen (12-18 yr), young adult (12-21 yr), adult (21+)
        - ~~Sex/gender~~
        - Measure type
            - EEG-based
                - Visual-[event related potentials](https://en.wikipedia.org/wiki/Event-related_potential) (VERP)
            - Eye tracking
            - fMRI
        - Behavior type
            - Button pressing
            - Verbal
            - Preferential looking
            - direction thresholds (temporal)
    - Seek data sets?
    
## Stimulus-specific subsets

- [Dot motion](dot-motion.md); Zhichun
- [Biological motion](biological-motion.md); Ashton
- [Grating-Plaid motion](dot-motion.md); Michelle

## Sources to look at more deeply

- Hadad, B.-S., Schwartz, S., Maurer, D., & Lewis, T. L. (2015). Motion perception: a review of developmental changes and the role of early visual experience. Frontiers in integrative neuroscience, 9, 49. Retrieved June 20, 2016, from http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4569849/
